MODEL_NAME: "vesteinn/ScandiBERT-no-faroese"
PATH_TO_DATA: "./data/Faroese.csv"
# OUTPUT_DIR: './results'

BATCH_SIZE: 8
TRAIN_TEST_SPLIT: 0.2
LEARNING_RATE: 2e-5
EPOCHS: 2
MAX_TOKENS: 514
NUMBER_EXAMPLES: 2000
MASK_PROBABILITY: 0.15
