seed: 42

model:
  name: 'vesteinn/ScandiBERT-no-faroese'

dataset:
  sentences: '${hydra:runtime.cwd}/data/Faroese.csv'
  train_test_split: 0.2
  mask_probability: 0.15
  max_tokens: 514
  n_examples: 2000

trainer:
  precision: 32
  epochs: 3
  batch_size: 16
  lr: 1e-4
  progress_bar_refresh_rate: 20
  log_dir: '${hydra:runtime.cwd}/results/mlm_logs'
  checkpoint_dir: '${hydra:runtime.cwd}/results/checkpoints'
  save_top_k: 1
