optimizer:
  type: "AdamW"
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.01
  lr: 0.00002
  warmup_steps: 0 # Add the warmup_steps wit ha default value
  total_steps: 100000 # Add the total_steps key with a default value
